const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Elenco delle mosse con i loro dettagli
const moves = [
    {
        name: 'Abbagliante',
        description: 'Chi la usa scatena un’esplosione abbagliante che può anche ridurre la Difesa Speciale del Pokémon colpito.',
        power: 70,
        accuracy: 100,
        pp: 5,
        types: ['Psico', 'Speciale'],
    },
    {
        name: 'Abbattimento',
        description: 'Chi la usa lancia una pietra o un proiettile. Può colpire anche un bersaglio in volo e farlo cadere.',
        power: 50,
        accuracy: 100,
        pp: 15,
        types: ['Roccia', 'Fisico'],
    },
    {
        name: 'Abbraccio Spettrale',
        description: 'Grazie al Potere Z, chi la usa intrappola il bersaglio in una morsa generata dal proprio rancore. La potenza varia a seconda della mossa su cui si basa.',
        power: 0,
        accuracy: 0,
        pp: 1,
        types: ['Spettro', 'Fisico'],
    },
    {
        name: 'Abisso',
        description: 'Chi la usa crea una spaccatura nel terreno e cerca di gettarvici dentro il bersaglio. Se va a segno, il Pokémon colpito va KO.',
        power: 0,
        accuracy: 30,
        pp: 5,
        types: ['Terra', 'Fisico'],
    },
    {
        name: 'Accumulo',
        description: 'Chi la usa accumula energia aumentando la Difesa e la Difesa Speciale. Si può utilizzare tre volte.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Acidiluvio Corrosivo',
        description: 'Chi la usa sfrutta il Potere Z per creare una palude velenosa che sommerge il bersaglio. La potenza varia a seconda della mossa su cui si basa.',
        power: 0,
        accuracy: 0,
        pp: 1,
        types: ['Veleno', 'Fisico'],
    },
    {
        name: 'Acido',
        description: 'Colpisce i nemici intorno spruzzando un acido corrosivo. Può anche ridurne la Difesa Speciale.',
        power: 40,
        accuracy: 100,
        pp: 30,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Acido Malico',
        description: 'Chi la usa attacca il bersaglio con un liquido acido ricavato da mele aspre riducendone la Difesa Speciale.',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Speciale'],
    },
    {
        name: 'Acidobomba',
        description: 'Chi la usa attacca il bersaglio con un acido altamente corrosivo. Il fluido riduce di molto la Difesa Speciale del bersaglio.',
        power: 40,
        accuracy: 100,
        pp: 20,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Acquadisale',
        description: 'Se i PS del bersaglio sono scesi a metà o meno, questa mossa colpirà con il doppio della potenza.',
        power: 65,
        accuracy: 100,
        pp: 10,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acquagetto',
        description: 'Chi la usa colpisce sempre per primo e a una tale velocità da rendersi quasi invisibile.',
        power: 40,
        accuracy: 100,
        pp: 20,
        types: ['Acqua', 'Fisico'],
    },
    {
        name: 'Acqualame',
        description: 'Chi la usa attacca sempre per primo, colpendo il bersaglio con uno shuriken di muco da due a cinque volte di fila.',
        power: 15,
        accuracy: 100,
        pp: 20,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acquanello',
        description: 'Chi la usa si avvolge in un velo d’acqua. Recupera alcuni PS a ogni turno.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Acqua', 'Stato'],
    },
    {
        name: 'Acquapatto',
        description: 'Attacca il bersaglio con una colonna d’acqua. Se usata con Fiammapatto, gli effetti aumentano e appare un arcobaleno.',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acrobazia',
        description: 'Attacca rapidamente il bersaglio. Se chi la usa non ha uno strumento, infligge al nemico grossi danni.',
        power: 55,
        accuracy: 100,
        pp: 15,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Acupressione',
        description: 'Chi la usa esercita pressione su alcuni punti nevralgici e aumenta di molto una statistica a caso.',
        power: 0,
        accuracy: 0,
        pp: 30,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Adesso Faccio sul Serio',
        description: 'Grazie al Potere Z, Snorlax tira fuori la grinta e, muovendo energicamente il suo enorme corpo, attacca il bersaglio con tutta la sua forza.',
        power: 210,
        accuracy: 0,
        pp: 1,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Adulazione',
        description: 'Adula il bersaglio e lo confonde, ma ne aumenta l’Attacco Speciale.',
        power: 0,
        accuracy: 100,
        pp: 15,
        types: ['Buio', 'Stato'],
    },
    {
        name: 'Aerasoio',
        description: 'Chi la usa provoca un vento tagliente che sferza i nemici intorno. Probabile brutto colpo.',
        power: 60,
        accuracy: 95,
        pp: 25,
        types: ['Volante', 'Speciale'],
    },
    {
        name: 'Aeroassalto',
        description: 'Chi la usa attacca il bersaglio a grande velocità. Questa mossa è infallibile.',
        power: 60,
        accuracy: 0,
        pp: 20,
        types: ['Volante', 'Fisico'],
    },
    {
        name: '',
        description: '',
        power: 0,
        accuracy: 0,
        pp: 0,
        types: [''],
    },
    {
        name: "Attacco Rapido",
        description: "Colpisce velocemente il nemico.",
        power: 40,
        accuracy: 100,
        pp: 30,
        types: ["Normale"],
    },
    {
        name: "Lanciafiamme",
        description: "Una potente fiammata che può bruciare il nemico.",
        power: 90,
        accuracy: 100,
        pp: 15,
        types: ["Fuoco"],
    },
    {
        name: "Idropompa",
        description: "Un getto d'acqua ad alta pressione.",
        power: 110,
        accuracy: 80,
        pp: 5,
        types: ["Acqua"],
    },
    // Aggiungi qui altre mosse...
];