const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Elenco delle mosse con i loro dettagli
const moves = [
    {
        name: 'Abbagliante',
        description: 'Chi la usa scatena un\'esplosione abbagliante che può anche ridurre la Difesa Speciale del Pokémon colpito.',
        power: 70,
        accuracy: 100,
        pp: 5,
        types: ['Psico', 'Speciale'],
    },
    {
        name: 'Abbattimento',
        description: 'Chi la usa lancia una pietra o un proiettile. Può colpire anche un bersaglio in volo e farlo cadere.',
        power: 50,
        accuracy: 100,
        pp: 15,
        types: ['Roccia', 'Fisico'],
    },
    {
        name: 'Abbraccio Spettrale',
        description: 'Grazie al Potere Z, chi la usa intrappola il bersaglio in una morsa generata dal proprio rancore. La potenza varia a seconda della mossa su cui si basa.',
        power: 0,
        accuracy: 0,
        pp: 1,
        types: ['Spettro', 'Fisico'],
    },
    {
        name: 'Abisso',
        description: 'Chi la usa crea una spaccatura nel terreno e cerca di gettarvici dentro il bersaglio. Se va a segno, il Pokémon colpito va KO.',
        power: 0,
        accuracy: 30,
        pp: 5,
        types: ['Terra', 'Fisico'],
    },
    {
        name: 'Accumulo',
        description: 'Chi la usa accumula energia aumentando la Difesa e la Difesa Speciale. Si può utilizzare tre volte.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Acidiluvio Corrosivo',
        description: 'Chi la usa sfrutta il Potere Z per creare una palude velenosa che sommerge il bersaglio. La potenza varia a seconda della mossa su cui si basa.',
        power: 0,
        accuracy: 0,
        pp: 1,
        types: ['Veleno', 'Fisico'],
    },
    {
        name: 'Acido',
        description: 'Colpisce i nemici intorno spruzzando un acido corrosivo. Può anche ridurne la Difesa Speciale.',
        power: 40,
        accuracy: 100,
        pp: 30,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Acido Malico',
        description: 'Chi la usa attacca il bersaglio con un liquido acido ricavato da mele aspre riducendone la Difesa Speciale.',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Speciale'],
    },
    {
        name: 'Acidobomba',
        description: 'Chi la usa attacca il bersaglio con un acido altamente corrosivo. Il fluido riduce di molto la Difesa Speciale del bersaglio.',
        power: 40,
        accuracy: 100,
        pp: 20,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Acquadisale',
        description: 'Se i PS del bersaglio sono scesi a metà o meno, questa mossa colpirà con il doppio della potenza.',
        power: 65,
        accuracy: 100,
        pp: 10,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acquagetto',
        description: 'Chi la usa colpisce sempre per primo e a una tale velocità da rendersi quasi invisibile.',
        power: 40,
        accuracy: 100,
        pp: 20,
        types: ['Acqua', 'Fisico'],
    },
    {
        name: 'Acqualame',
        description: 'Chi la usa attacca sempre per primo, colpendo il bersaglio con uno shuriken di muco da due a cinque volte di fila.',
        power: 15,
        accuracy: 100,
        pp: 20,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acquanello',
        description: 'Chi la usa si avvolge in un velo d\'acqua. Recupera alcuni PS a ogni turno.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Acqua', 'Stato'],
    },
    {
        name: 'Acquapatto',
        description: 'Attacca il bersaglio con una colonna d\'acqua. Se usata con Fiammapatto, gli effetti aumentano e appare un arcobaleno.',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Acqua', 'Speciale'],
    },
    {
        name: 'Acrobazia',
        description: 'Attacca rapidamente il bersaglio. Se chi la usa non ha uno strumento, infligge al nemico grossi danni.',
        power: 55,
        accuracy: 100,
        pp: 15,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Acupressione',
        description: 'Chi la usa esercita pressione su alcuni punti nevralgici e aumenta di molto una statistica a caso.',
        power: 0,
        accuracy: 0,
        pp: 30,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Adesso Faccio sul Serio',
        description: 'Grazie al Potere Z, Snorlax tira fuori la grinta e, muovendo energicamente il suo enorme corpo, attacca il bersaglio con tutta la sua forza.',
        power: 210,
        accuracy: 0,
        pp: 1,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Adulazione',
        description: 'Adula il bersaglio e lo confonde, ma ne aumenta l\'Attacco Speciale.',
        power: 0,
        accuracy: 100,
        pp: 15,
        types: ['Buio', 'Stato'],
    },
    {
        name: 'Aerasoio',
        description: 'Chi la usa provoca un vento tagliente che sferza i nemici intorno. Probabile brutto colpo.',
        power: 60,
        accuracy: 95,
        pp: 25,
        types: ['Volante', 'Speciale'],
    },
    {
        name: 'Aeroassalto',
        description: 'Chi la usa attacca il bersaglio a grande velocità. Questa mossa è infallibile.',
        power: 60,
        accuracy: 0,
        pp: 20,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Aeroattacco',
        description: 'Attacco in due turni e probabile brutto colpo. Può anche far tentennare il bersaglio.',
        power: 140,
        accuracy: 90,
        pp: 5,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Aerocolpo',
        description: 'Colpisce il bersaglio con un vortice d\'aria per danneggiarlo. Probabile brutto colpo.',
        power: 100,
        accuracy: 95,
        pp: 5,
        types: [''],
    },
    {
        name: 'Affannoseme',
        description: 'Un seme che causa ansia viene piantato sul bersaglio. Ne muta l\'abilità in Insonnia e ne previene o rimuove il sonno.',
        power: 0,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Affilatore',
        description: 'Chi la usa riduce il numero di poligoni sul proprio corpo per accentuarne gli spigoli e aumentare l\'Attacco.',
        power: 0,
        accuracy: 0,
        pp: 30,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Agilità',
        description: 'Chi la usa rilassa e alleggerisce il proprio corpo per far salire di molto la Velocità.',
        power: 0,
        accuracy: 0,
        pp: 30,
        types: ['Fisico', 'Stato'],
    },
    {
        name: 'Agodifesa',
        description: 'Protegge dagli attacchi, riducendo inoltre i PS dei Pokémon che entrano in contatto con chi la usa.',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Alacciaio',
        description: 'Colpisce il bersaglio con ali d\'acciaio. Può anche aumentare la Difesa di chi la usa.',
        power: 70,
        accuracy: 90,
        pp: 25,
        types: ['Acciaio', 'Fisico'],
    },
    {
        name: 'Ali d\'Aura',
        description: '',
        power: 80,
        accuracy: 100,
        pp: 0,
        types: ['Psico', 'Speciale'],
    },
    {
        name: 'Ali del Fato',
        description: 'Chi la usa assorbe energia dal bersaglio recuperando una quantità di PS pari a più della metà del danno inferto.',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Volante', 'Speciale'],
    },
    {
        name: 'Alitogelido',
        description: 'Chi la usa attacca il bersaglio con un soffio d\'aria gelida. Brutto colpo assicurato.',
        power: 60,
        accuracy: 90,
        pp: 10,
        types: ['Ghiaccio', 'Speciale'],
    },
    {
        name: 'Alleggerimento',
        description: '',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Alta Cucina',
        description: '',
        power: 80,
        accuracy: 100,
        pp: 10,
        types: ['Drago', 'Psico'],
    },
    {
        name: 'Altruismo',
        description: 'Mossa che aumenta la potenza dell\'attacco di un alleato.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Amnesia',
        description: 'Chi la usa svuota per un po\' la mente per dimenticare i problemi. La Difesa Speciale aumenta di molto.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Psico', 'Stato'],
    },
    {
        name: 'Anticipo',
        description: 'Chi la usa protegge sé e gli alleati dalle mosse dei nemici che fanno colpire per primi.',
        power: 0,
        accuracy: 0,
        pp: 15,
        types: ['Lotta', 'Stato'],
    },
    {
        name: 'Anticura',
        description: 'Chi la usa impedisce ai nemici che ha intorno di utilizzare mosse o abilità recupera-PS per cinque turni.',
        power: 0,
        accuracy: 100,
        pp: 15,
        types: ['Psico', 'Stato'],
    },
    {
        name: 'Apripista',
        description: '',
        power: 50,
        accuracy: 100,
        pp: 20,
        types: ['Erba', 'Fisico'],
    },
    {
        name: 'Aracampo',
        description: 'Chi la usa dissoda la terra per far crescere meglio l\'erba. Questa mossa aumenta l\'Attacco e l\'Attacco Speciale dei Pokémon di tipo Erba.',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Terra', 'Stato'],
    },
    {
        name: 'Armaguscio',
        description: 'Il Pokémon esegue un attacco fisico o speciale, in base a quale causa danni maggiori. Può anche avvelenare il bersaglio.',
        power: 90,
        accuracy: 100,
        pp: 10,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Aromaterapia',
        description: 'Chi la usa rilascia un dolce profumo che cura tutti i problemi di stato propri e degli alleati.',
        power: 0,
        accuracy: 0,
        pp: 5,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Arrotola',
        description: 'Chi la usa si concentra aumentando Attacco, Difesa e precisione.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Veleno', 'Stato'],
    },
    {
        name: 'Artigli Fatali',
        description: '',
        power: 80,
        accuracy: 100,
        pp: 15,
        types: ['Veleno', 'Fisico'],
    },
    {
        name: 'Ascesa del Drago',
        description: 'Permette di proiettarsi in aria e fiondarsi sul bersaglio attaccando ad altissima velocità. Riduce la Difesa e la Difesa Speciale di chi la usa.',
        power: 120,
        accuracy: 100,
        pp: 5,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Assalto',
        description: 'Chi la usa si lancia con tutte le sue forze sul bersaglio e ne riduce l\'Attacco.',
        power: 80,
        accuracy: 100,
        pp: 15,
        types: ['Coleottero', 'Fisico'],
    },
    {
        name: 'Assillo',
        description: 'Chi la usa lancia un attacco che tormenta il bersaglio per quattro o cinque turni, durante i quali gli impedisce di fuggire.',
        power: 20,
        accuracy: 100,
        pp: 20,
        types: ['Coleottero', 'Speciale'],
    },
    {
        name: 'Assistente',
        description: 'Chi la usa utilizza in fretta e a caso una delle mosse degli altri Pokémon della squadra.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Asso',
        description: 'La potenza di questa mossa aumenta man mano che i suoi PP diminuiscono.',
        power: 0,
        accuracy: 0,
        pp: 5,
        types: ['Normale', 'Speciale'],
    },
    {
        name: 'Assorbibacio',
        description: 'Chi la usa assorbe energia dal bersaglio con un bacio, recuperando così PS in quantità pari a più della metà del danno inferto.',
        power: 50,
        accuracy: 100,
        pp: 10,
        types: ['Folletto', 'Speciale'],
    },
    {
        name: 'Assorbiforza',
        description: 'Fa recuperare una quantità di PS pari all\'Attacco del bersaglio, che vedrà diminuire questa statistica.',
        power: 0,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Assorbimento',
        description: 'Mossa che assorbe PS. Chi la usa recupera una quantità di PS pari alla metà del danno inferto.',
        power: 20,
        accuracy: 100,
        pp: 25,
        types: ['Erba', 'Speciale'],
    },
    {
        name: 'Astrocarica',
        description: 'Chi la usa travolge il bersaglio con la potenza di una meteora. Questo attacco ignora l\'abilità del bersaglio.',
        power: 100,
        accuracy: 100,
        pp: 5,
        types: ['Acciaio', 'Fisico'],
    },
    {
        name: 'Astroimpatto Fatato',
        description: 'Grazie al Potere Z, chi la usa crea una dimensione fatata in cui fa ciò che vuole del proprio bersaglio. La potenza varia a seconda della mossa su cui si basa.',
        power: 0,
        accuracy: 0,
        pp: 1,
        types: ['Folletto', 'Fisico'],
    },
    {
        name: 'Attaccalite',
        description: 'Chi la usa tormenta e fa infuriare il bersaglio, impedendogli di usare la stessa mossa due volte di seguito.',
        power: 0,
        accuracy: 100,
        pp: 15,
        types: ['Buio', 'Stato'],
    },
    {
        name: 'Attacco Pioggia',
        description: 'Piovono enormi sfere sulla testa del bersaglio da due a cinque volte di fila.',
        power: 15,
        accuracy: 85,
        pp: 20,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Attacco Rapido',
        description: 'Chi la usa colpisce sempre per primo e a una tale velocità da rendersi quasi invisibile.',
        power: 40,
        accuracy: 100,
        pp: 30,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Attacco d\'Ala',
        description: 'Infligge danni al bersaglio spiegando delle grandi ali possenti.',
        power: 60,
        accuracy: 100,
        pp: 35,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Attrazione',
        description: 'Se il bersaglio è del sesso opposto, s\'infatua e diventa riluttante ad attaccare.',
        power: 0,
        accuracy: 100,
        pp: 15,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Auguri',
        description: 'Il Pokémon ti fa gli auguri nel tuo giorno speciale.',
        power: 0,
        accuracy: 0,
        pp: 40,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Auraswoosh',
        description: 'Colpisce il bersaglio ripetutamente con onde di forza psicocinetica e innalza una barriera fantastica che riduce i danni degli attacchi speciali nemici.',
        power: 80,
        accuracy: 95,
        pp: 15,
        types: ['Psico', 'Speciale'],
    },
    {
        name: 'Autodistruzione',
        description: 'Chi la usa esplode e infligge danni ai Pokémon che ha intorno, ma poi va KO.',
        power: 200,
        accuracy: 100,
        pp: 5,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Avvolgibotta',
        description: 'Il lungo corpo o le liane di chi la usa avvolgono e stritolano il bersaglio per quattro o cinque turni.',
        power: 15,
        accuracy: 90,
        pp: 20,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Azione',
        description: 'Attacco fisico che colpisce il bersaglio investendolo con tutto il corpo.',
        power: 40,
        accuracy: 100,
        pp: 35,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Azzardo',
        description: 'Chi la usa attacca con tutta la potenza di cui dispone e va KO, ma infligge al bersaglio un danno pari ai PS che ha perso.',
        power: 0,
        accuracy: 100,
        pp: 5,
        types: ['Lotta', 'Speciale'],
    },
    {
        name: 'Baldeali',
        description: 'Chi la usa si nasconde sotto le ali e carica da bassa quota. Tuttavia, subisce considerevoli danni.',
        power: 120,
        accuracy: 100,
        pp: 15,
        types: ['Volante', 'Fisico'],
    },
    {
        name: 'Baldimpulso',
        description: '',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Psico', 'Stato'],
    },
    {
        name: 'Bottintesta',
        description: 'Chi la usa si lancia diritto di testa contro il bersaglio. Può anche farlo tentennare.',
        power: 70,
        accuracy: 100,
        pp: 15,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Corposcontro',
        description: 'Chi la usa carica il bersaglio con tutto il corpo. Può causarne anche la paralisi.',
        power: 85,
        accuracy: 100,
        pp: 15,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Crescita',
        description: 'Provoca la crescita immediata del corpo e l\'aumento dell\'Attacco e dell\'Attacco Speciale di chi la usa.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Cuordileone',
        description: 'Chi la usa si tira su di morale, aumentando il proprio Attacco e l’Attacco Speciale.',
        power: 0,
        accuracy: 0,
        pp: 30,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Danzaspada',
        description: 'Danza frenetica che incrementa lo spirito combattivo. Chi la usa aumenta di molto il suo Attacco.',
        power: 0,
        accuracy: 0,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Energipalla',
        description: 'Chi la usa attinge energia dalla natura e la scaglia contro il bersaglio. Può anche ridurne la Difesa Speciale.',
        power: 90,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Speciale'],
    },
    {
        name: 'Fangobomba',
        description: 'Lancio di fango malsano che arreca danno al bersaglio. Può anche avvelenarlo.',
        power: 90,
        accuracy: 100,
        pp: 10,
        types: ['Veleno', 'Speciale'],
    },
    {
        name: 'Flash',
        description: 'Investe il bersaglio con una luce abbagliante che ne riduce la precisione.',
        power: 0,
        accuracy: 100,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Foglielama',
        description: 'Foglie taglienti sferzano i nemici intorno. Probabile brutto colpo.',
        power: 55,
        accuracy: 95,
        pp: 25,
        types: ['Erba', 'Fisico'],
    },
    {
        name: 'Forza',
        description: 'Colpisce il bersaglio con un\'enorme energia. Fuori dalla lotta si usa per spostare i massi.',
        power: 80,
        accuracy: 100,
        pp: 15,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Frustata',
        description: 'Infligge danni al bersaglio con liane sottili simili a fruste.',
        power: 0,
        accuracy: 100,
        pp: 40,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Laccioerboso',
        description: 'Chi la usa intrappola il bersaglio con l\'erba e lo fa cadere. Danneggia maggiormente i Pokémon più pesanti.',
        power: 0,
        accuracy: 100,
        pp: 20,
        types: ['Erba', 'Speciale'],
    },
    {
        name: "Lanciafiamme",
        description: "Una potente fiammata che può bruciare il nemico.",
        power: 90,
        accuracy: 100,
        pp: 15,
        types: ["Fuoco"],
    },
    {
        name: "Idropompa",
        description: "Un getto d'acqua ad alta pressione.",
        power: 110,
        accuracy: 80,
        pp: 5,
        types: ["Acqua"],
    },
    {
        name: 'Oltraggio',
        description: 'Chi la usa sfoga la sua ira e attacca il nemico per due o tre turni prima di essere lasciato in preda alla confusione.',
        power: 120,
        accuracy: 100,
        pp: 10,
        types: ['Drago', 'Fisico'],
    },
    {
        name: 'Parassiseme',
        description: 'Vengono piantati semi sul bersaglio. Questi sottraggono PS a ogni turno permettendo a chi la usa di curarsi.',
        power: 0,
        accuracy: 90,
        pp: 10,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Profumino',
        description: 'Un dolce profumo che riduce di molto l\'elusione dei nemici intorno a chi la usa. Fuori dalla lotta attira i Pokémon selvatici.',
        power: 0,
        accuracy: 10,
        pp: 20,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Resistenza',
        description: 'Chi la usa resta con un PS anche se subisce un colpo da KO in quel turno. Usata in successione può fallire.',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Ruggito',
        description: 'Distrae i nemici intorno con un ruggito potente e ne ridue l\'Attacco.',
        power: 0,
        accuracy: 100,
        pp: 40,
        types: ['Normale', 'Stato',],
    },
    {
        name: 'Semebomba',
        description: 'Chi la usa emette una raffica di semi dal guscio duro che colpiscono il bersaglio dall\'alto.',
        power: 80,
        accuracy: 100,
        pp: 15,
        types: ['Erba', 'Fisico'],
    },
    {
        name: 'Sintesi',
        description: 'Chi la usa recupera PS. Il numero di PS recuperati dipende dalle condizioni atmosferiche.',
        power: 0,
        accuracy: 0,
        pp: 5,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Solarraggio',
        description: 'Chi la usa assorbe luce al primo turno per proiettare un raggio intenso al turno successivo.',
        power: 120,
        accuracy: 100,
        pp: 10,
        types: ['Erba', 'Speciale'],
    },
    {
        name: 'Sonnifero',
        description: 'Investe il bersaglio con una grande nuvola di polvere soporifera che lo fa addormentare.',
        power: 0,
        accuracy: 75,
        pp: 15,
        types: ['Erba', 'Stato'],
    },
    {
        name: 'Sonnolalia',
        description: 'Chi la usa sfodera a caso una delle proprie mosse mentre sta dormendo.',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Sostituto',
        description: 'Chi la usa crea una copia di se stesso usando alcuni PS. La copia serve come esca per il nemico.',
        power: 0,
        accuracy: 0,
        pp: 10,
        types: ['Normale', 'Stato'],
    },
    {
        name: 'Spaccaroccia',
        description: 'Chi la usa colpisce il bersaglio con un pugno in grado di frantumare anche la roccia. Può anche ridurne la Difesa.',
        power: 40,
        accuracy: 100,
        pp: 15,
        types: ['Lotta', 'Fisico'],
    },
    {
        name: 'Taglio',
        description: 'Attacca il bersaglio con artigli o falci affilate. Fuori dalla lotta si usa per tagliare piccoli alberi.',
        power: 50,
        accuracy: 95,
        pp: 30,
        types: ['Normale', 'Fisico'],
    },
    {
        name: 'Velenpolvere',
        description: 'Investe il bersaglio con una nuvola di polvere tossica che avvelena.',
        power: 0,
        accuracy: 75,
        pp: 35,
        types: ['Veleno', 'Stato'],
    }
    // Aggiungi qui altre mosse...
];

async function main() {
    console.log("Inizio popolamento mosse Pokémon...");

    for (const move of moves) {
        // Controlla se la mossa esiste già nel database
        const existingMove = await prisma.move.findUnique({
            where: { name: move.name },
        });

        if (existingMove) {
            // Verifica se i dati sono identici
            const isIdentical =
                existingMove.description === move.description &&
                existingMove.power === move.power &&
                existingMove.accuracy === move.accuracy &&
                existingMove.pp === move.pp;

            if (isIdentical) {
                continue;
            }

            // Aggiorna i dati se non sono allineati
            await prisma.move.update({
                where: { name: move.name },
                data: {
                    description: move.description,
                    power: move.power,
                    accuracy: move.accuracy,
                    pp: move.pp,
                },
            });

            console.log(`"${move.name}" aggiornata.`);
        } else {
            // Crea la mossa da zero
            const createdMove = await prisma.move.create({
                data: {
                    name: move.name,
                    description: move.description,
                    power: move.power,
                    accuracy: move.accuracy,
                    pp: move.pp,
                },
            });

            console.log(`"${move.name}" creata.`);
        }

        // Associa i tipi alla mossa
        for (const typeName of move.types) {
            const type = await prisma.type.findUnique({
                where: { name: typeName },
            });

            if (type) {
                await prisma.move.update({
                    where: { name: move.name },
                    data: {
                        types: {
                            connect: { id: type.id },
                        },
                    },
                });
                console.log(`Tipo "${typeName}" associato alla mossa "${move.name}".`);
            } else {
                console.warn(`Tipo "${typeName}" non trovato per la mossa "${move.name}".`);
            }
        }
    }

    console.log("Popolamento delle mosse completato!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });